package com.test.school.Student;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping(path="/school") // This means URL's start with /demo (after Application path)
public class EstudianteController {

	@Autowired // This means to get the bean called estudianteRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private EstudianteRepository estudianteRepository;
	
	@Autowired
	IEstudianteService studentService;	
	
	@GetMapping(path="/student")
	public @ResponseBody Iterable<Estudiante> getAllStudent() {
		// This returns a JSON or XML with the students
		return estudianteRepository.findAll();
	}
	
	@RequestMapping(value="/saveStudent",method=RequestMethod.POST)
    public Boolean saveStudent(@RequestBody Estudiante student){
          return studentService.saveStudent(student);
    }

	@RequestMapping(value="/updateStudent",method=RequestMethod.PUT)
    public Boolean updateStudent(@RequestBody Estudiante student){
          return studentService.updateStudent(student);
    }
	
	@RequestMapping(value="/deleteStudent",method=RequestMethod.DELETE)
	public void deleteStudent(Estudiante student) {
		studentService.deleteStudent(student);
	}
		
}

