package com.test.school.Course;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping(path="/school") // This means URL's start with /demo (after Application path)
public class CursosController {

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private CursosRepository cursosRepository;
	
	@Autowired
	ICursosService courseService;	
	
	@GetMapping(path="/courses")
	public @ResponseBody Iterable<Cursos> getAllCourses() {
		// This returns a JSON or XML with the courses
		return cursosRepository.findAll();
	}
	
	@RequestMapping(value="/saveCourses",method=RequestMethod.POST)
    public Boolean saveCourses(@RequestBody Cursos course){
          return courseService.saveCourses(course);
    }

	@RequestMapping(value="/updateCourses",method=RequestMethod.PUT)
    public Boolean updateCourses(@RequestBody Cursos course){
          return courseService.updateCourses(course);
    }

	
	@RequestMapping(value="/deleteCourses",method=RequestMethod.DELETE)
	public void deleteCourses(Cursos course) {
		courseService.deleteCourses(course);
	}
		
}
