package com.test.school.School;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping(path="/school") // This means URL's start with /demo (after Application path)
public class ColegioController {

	@Autowired // This means to get the bean called colegioRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private ColegioRepository colegioRepository;
	
	@Autowired
	IColegioService schoolService;	
	
	@GetMapping(path="/school")
	public @ResponseBody Iterable<Colegio> getAllSchool() {
		// This returns a JSON or XML with the schools
		return colegioRepository.findAll();
	}
	
	@RequestMapping(value="/saveSchool",method=RequestMethod.POST)
    public Boolean saveSchool(@RequestBody Colegio school){
          return schoolService.saveSchool(school);
    }

	@RequestMapping(value="/updateSchool",method=RequestMethod.PUT)
    public Boolean updateCourses(@RequestBody Colegio school){
          return schoolService.updateSchool(school);
    }

	
	@RequestMapping(value="/deleteSchool",method=RequestMethod.DELETE)
	public void deleteSchool(Colegio school) {
		schoolService.deleteSchool(school);
	}
		
}

